### ISSUE TITLE
Running into command 'armJsonOutline.openArmOutline' not found

### ISSUE THREAD

**Issue by thelethalkind** [GoEddie/armed-docs#1]
Hey there, I've installed this extension, opened my arm template and I've tried running ARM: Start Outliner but I'm getting back this error: 

command 'armJsonOutline.openArmOutline' not found

Is there anything I'm missing maybe?

**Comment by GoEddie** [comment]
Hi,

What version do you have installed?

Ed

**Comment by GoEddie** [comment]
Hi sorry there was a dependency missing, if you grab the latest it should work now!

**Comment by thelethalkind** [comment]
It's working now, thank you!
