### ISSUE TITLE
The dependency graph is cropped

### ISSUE THREAD

**Issue by MWL88** [GoEddie/armed-docs#2]
When I try to display the dependency graph of any ARM template the graph's image is cropped.

![image](https://user-images.githubusercontent.com/14333900/34168281-05911572-e4dc-11e7-819a-47dfe82e2a7c.png)

**Comment by GoEddie** [comment]
Hi,

I’ll include something in the next release to help this.

Question:

If you have the dependency graph open, go back to the json and generate it again, is it still cropped?


Ed

**Comment by MWL88** [comment]
Hi,

When opening the dependency graph, the cropping issue occurs the majority of the time however, it is intermittent. I unfortunately cannot provide a specific scenario to reproduce the issue (or not reproduce the issue)

In answer to you question: yes the dependency graph is still cropped.

When the dependency graph is opened correctly, if I then switch to another VS Code editor tab (within the same window) and then switch back to the dependency graph ... the dependency graph is now cropped.

Thanks

**Comment by GoEddie** [comment]
I have pushed a newer version which delays when I get the height and width - can you try that? If it still fails let me know and I have added some debugging to help see what is wrong.

**Comment by GoEddie** [comment]
hey, i'll assume the latest build fixed this and close this now - if it doesn't just re-open it and I will look at it :)

**Comment by MWL88** [comment]
Hi,

I have version 0.0.17 installed and the issue still occurs.

Where do I enable / find the debugging output to help you diagnose this issue?

Thanks
Mark
