### ISSUE TITLE
Error: Couldn't find a compatible version of Azure ARM Template Helper with this version of Code.

### ISSUE THREAD

**Issue by frederick-esparagoza-swo** [GoEddie/armed-docs#3]
Getting an error when installing extension: Couldn't find a compatible version of Azure ARM Template Helper with this version of Code.

**Comment by GoEddie** [comment]
What version of vscode do you have?

**Comment by frederick-esparagoza-swo** [comment]
Was on 1.16… upgraded to 1.19 and it worked… thanks ed… extension was awesome!

Thanks,

Fred Esparagoza | SoftwareONE | +65 9364 6024

**Comment by GoEddie** [comment]
Great :)
