### ISSUE TITLE
treeview stopped workign in the latest vscode build

### ISSUE THREAD

**Issue by GoEddie** [GoEddie/armed-docs#5]
The latest vscode build broke the treeview, see: https://github.com/Azure/azure-powershell/issues/4835

If you get the latest insiders build that works - when they release a version of the stable build with the fix in I will update the extension to require that as a base version.

**Comment by brwilkinson** [comment]
I think the latest Insiders build stopped working as well?

**Comment by GoEddie** [comment]
hi! what version have you got? I just tested with 1.23.0-insider and that seems to work?

**Comment by brwilkinson** [comment]
I cannot see the view anywhere? I update the Insiders build every day. . . currently 1.24.0-insider

It did work for me for 1 day, then after the next update stopped working.

I don't know where to find the logs or anything . .  when I run F1 --> ARM Start Outliner, . . nothing happens.

If I look in View --> open views I don't see anything in there for the extension?


I tried uninstalling/reinstalling enabling/disabling etc...

**Comment by GoEddie** [comment]
I just installed 1.24.0-insider and it seems to work fine here, does anything from the extension work? 

If you try using "ARM: Test Expression" and something like "add(1,1)" does the output window pop up and show "[add(1,1)] evaluated to: 2"?

If you try and start the outliner then do Help --> toggle dev tools, does it show any errors (stack traces?)

Do you have a valid ARM template in a .json file open?

ed

**Comment by brwilkinson** [comment]
Hey @GoEddie 

The extension is not working at all it seems.

When I run the ARML Test Expression, nothing runs.

How can I get more info ? I don't see anything in any logs?!

**Comment by brwilkinson** [comment]
Okay I figured it out. . . 

JSON outline doesn't show up when file type changed from Plain Text to JSON or JSONC
https://github.com/Microsoft/vscode-azurearmtools/issues/98

**Comment by brwilkinson** [comment]
Feel free to closed this.

**Comment by GoEddie** [comment]
ta :)
